import json
import re

from app.models import (
    BookingChecklistItem,
    BookingStatus,
    DestinationPack,
    Itinerary,
    ItineraryDay,
    ItinerarySegment,
    ItinerarySummary,
    MapPlace,
    PlaceCategory,
    PlanTripRequest,
    ReminderGroup,
)
from app.agent.request_helpers import dates_for_request, days_from_prompt, destination_for_request, slug
from app.data.packing_rules import merge_reminders


def itinerary_from_gemini(
    request: PlanTripRequest,
    base_itinerary: Itinerary,
    destination_pack: DestinationPack,
    generated: dict,
) -> Itinerary | None:
    """Convert Gemini's JSON object into the app's typed itinerary model."""
    try:
        profile = request.profile or base_itinerary.profile
        destination = destination_for_request(request)
        days_count = request.days or days_from_prompt(request.prompt) or 5
        places = _places_from_generated(generated, destination)
        days = _days_from_generated(generated, places, days_count)
        if not days:
            return None

        import time
        trip_id = f"{destination_pack.id}-{int(time.time())}"
        return Itinerary(
            id=trip_id,
            title=_string(generated.get("title"), f"{destination} Trip"),
            subtitle=_string(
                generated.get("subtitle"),
                f"Personalized {days_count}-day route for {destination}.",
            ),
            dates=dates_for_request(request, days_count),
            destination_pack_id=destination_pack.id,
            summary=_summary_from_generated(generated),
            profile=profile,
            places=places,
            days=days,
            reminders=merge_reminders(_reminders_from_generated(generated), destination_pack.id),
            booking_checklist=_booking_from_generated(generated, destination),
            assumptions=_list_of_strings(generated.get("assumptions"))[:5] or [
                "Generated by Gemini for planning only; verify live hours and routes before booking.",
                "No real booking is performed in this demo.",
            ],
        )
    except (TypeError, ValueError, KeyError):
        return None


def parse_skeleton(text: str) -> list[dict]:
    """Parse Gemini skeleton output into list of {day_number, city} dicts."""
    text = strip_fences(text)
    try:
        raw = json.loads(text)
    except json.JSONDecodeError:
        return []
    if not isinstance(raw, list):
        return []
    result = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        day = item.get("day") or item.get("day_number") or len(result) + 1
        city = item.get("city") or item.get("area") or ""
        if city:
            result.append({"day_number": int(day), "city": str(city).strip()})
    return result


def parse_day_allocation_string(day_allocation: str) -> list[dict]:
    """Parse 'D1: Tokyo, D2: Kyoto' into [{day_number, city}, ...]."""
    if not day_allocation:
        return []
    skeleton = []
    for part in day_allocation.split(","):
        part = part.strip()
        match = re.match(r"D(\d+):\s*(.+)", part)
        if match:
            skeleton.append({"day_number": int(match.group(1)), "city": match.group(2).strip()})
    return skeleton


def strip_fences(text: str) -> str:
    """Remove markdown code fences that Gemini sometimes wraps around JSON."""
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-z]*\n?", "", text)
        text = re.sub(r"\n?```$", "", text)
    return text.strip()


def normalize_chat_answer(text: str) -> str:
    clean_text = text.strip()
    if not clean_text:
        return ""
    try:
        parsed = json.loads(clean_text)
    except json.JSONDecodeError:
        return clean_text
    if isinstance(parsed, dict):
        for key in ("answer", "response", "content", "text"):
            value = parsed.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return clean_text


def _summary_from_generated(generated: dict) -> ItinerarySummary:
    summary = generated.get("summary")
    if not isinstance(summary, dict):
        summary = {}
    return ItinerarySummary(
        hotel=_string(summary.get("hotel"), "Stay near transit and the main evening area."),
        flights=_string(summary.get("flights"), "Prepare flight search handoff."),
        transit=_string(summary.get("transit"), "Use local transit plus taxis when it protects pacing."),
        budget=_string(summary.get("budget"), "Use local currency; verify exchange rate before booking."),
    )


def _places_from_generated(generated: dict, destination: str) -> list[MapPlace]:
    raw_places = generated.get("places")
    if not isinstance(raw_places, list):
        raw_places = []

    places: list[MapPlace] = []
    for index, raw in enumerate(raw_places[:24], start=1):
        if not isinstance(raw, dict):
            continue
        name = _string(raw.get("name"), f"Stop {index}")
        place_id = slug(_string(raw.get("id"), name))
        category = _category(raw.get("category"))
        query = _string(raw.get("google_maps_query"), f"{name} {destination}")
        lat = float(raw.get("lat") or 0)
        lng = float(raw.get("lng") or 0)
        places.append(
            MapPlace(
                id=place_id,
                name=name,
                category=category,
                neighborhood=_string(raw.get("neighborhood"), destination),
                lat=lat,
                lng=lng,
                cost=_string(raw.get("cost"), "$"),
                duration=_string(raw.get("duration"), "1-2 hr"),
                source="gemini-function-calling",
                why_it_fits=_string(raw.get("why_it_fits"), "Fits the requested trip style."),
                google_maps_url=f"https://www.google.com/maps/search/?api=1&query={query.replace(' ', '+')}",
                google_place_id=_string(raw.get("google_place_id") or raw.get("place_id"), ""),
            ),
        )
    return places


def _days_from_generated(generated: dict, places: list[MapPlace], fallback_days: int) -> list[ItineraryDay]:
    raw_days = generated.get("days")
    if not isinstance(raw_days, list):
        return []
    place_ids = {place.id for place in places}
    days: list[ItineraryDay] = []
    colors = ["#2563eb", "#16a34a", "#f97316", "#9333ea", "#dc2626", "#0f766e", "#64748b"]

    for index, raw in enumerate(raw_days[:fallback_days], start=1):
        if not isinstance(raw, dict):
            continue
        raw_segments = raw.get("segments")
        if not isinstance(raw_segments, list):
            raw_segments = []
        segments: list[ItinerarySegment] = []
        used_place_ids: list[str] = []
        for seg_index, segment in enumerate(raw_segments[:6], start=1):
            if not isinstance(segment, dict):
                continue
            place_id = slug(_string(segment.get("place_id"), ""))
            seg_place_ids = [place_id] if place_id in place_ids else []
            used_place_ids.extend(seg_place_ids)
            segments.append(
                ItinerarySegment(
                    time=_string(segment.get("time"), f"Stop {seg_index}"),
                    title=_string(segment.get("title"), f"Activity {seg_index}"),
                    description=_string(segment.get("description"), "Tourist-friendly stop with local context."),
                    place_ids=seg_place_ids,
                    travel_note=_string(segment.get("travel_note"), "Check route timing before departure."),
                    cost=_string(segment.get("cost"), "$"),
                ),
            )
        if not segments:
            continue
        day_number = int(raw.get("day_number") or index)
        days.append(
            ItineraryDay(
                id=f"day-{day_number}",
                day_number=day_number,
                date=_string(raw.get("date"), f"Day {day_number}"),
                title=_string(raw.get("title"), f"Day {day_number}"),
                area=_string(raw.get("area"), "Route"),
                color=_string(raw.get("color"), colors[(index - 1) % len(colors)]),
                segments=segments,
                place_ids=list(dict.fromkeys(used_place_ids)),
            ),
        )
    return days


def _reminders_from_generated(generated: dict) -> list[ReminderGroup]:
    raw = generated.get("reminders")
    reminders: list[ReminderGroup] = []
    if isinstance(raw, list):
        for index, group in enumerate(raw[:4], start=1):
            if not isinstance(group, dict):
                continue
            items = _list_of_strings(group.get("items"))[:6]
            if items:
                reminders.append(
                    ReminderGroup(title=_string(group.get("title"), f"Reminder {index}"), items=items)
                )
    return reminders or [
        ReminderGroup(title="Packing", items=["Comfortable walking shoes", "Portable charger", "Weather layer"])
    ]


def _booking_from_generated(generated: dict, destination: str) -> list[BookingChecklistItem]:
    raw = generated.get("booking_checklist")
    items: list[BookingChecklistItem] = []
    if isinstance(raw, list):
        for index, item in enumerate(raw[:8], start=1):
            if not isinstance(item, dict):
                continue
            title = _string(item.get("title"), f"Prepare booking task {index}")
            items.append(
                BookingChecklistItem(
                    id=slug(_string(item.get("id"), title)),
                    type=_booking_type(item.get("type")),
                    title=title,
                    provider=_string(item.get("provider"), "Search handoff"),
                    status=_booking_status(item.get("status")),
                    deadline=_string(item.get("deadline"), "Before finalizing"),
                    action_label=_string(item.get("action_label"), "Prepare search"),
                    handoff_url=_string(
                        item.get("handoff_url"),
                        f"https://www.google.com/search?q={title.replace(' ', '+')}+{destination.replace(' ', '+')}",
                    ),
                ),
            )

    if not any(item.type == "flight" for item in items):
        items.insert(0, _fallback_flight_item(destination))
    if not any(item.type == "hotel" for item in items):
        items.insert(1, _fallback_hotel_item(destination))
    return items or [_fallback_flight_item(destination)]


def _fallback_flight_item(destination: str) -> BookingChecklistItem:
    return BookingChecklistItem(
        id="flight-handoff",
        type="flight",
        title=f"Prepare air ticket search for {destination}",
        provider="Flight search handoff",
        status=BookingStatus.needs_review,
        deadline="Before price alert expires",
        action_label="Search flights",
        handoff_url="https://www.google.com/travel/flights",
    )


def _fallback_hotel_item(destination: str) -> BookingChecklistItem:
    return BookingChecklistItem(
        id="hotel-area-handoff",
        type="hotel",
        title=f"Compare hotel areas for {destination}",
        provider="Hotel map handoff",
        status=BookingStatus.needs_review,
        deadline="Before finalizing route",
        action_label="Compare hotels",
        handoff_url=f"https://www.google.com/maps/search/{destination.replace(' ', '+')}+hotels",
    )


def _category(value: object) -> PlaceCategory:
    try:
        return PlaceCategory(str(value).lower())
    except ValueError:
        return PlaceCategory.attraction


def _booking_type(value: object) -> str:
    allowed = {"flight", "hotel", "restaurant", "ticket", "calendar"}
    text = str(value).lower()
    return text if text in allowed else "ticket"


def _booking_status(value: object) -> BookingStatus:
    try:
        return BookingStatus(str(value).lower())
    except ValueError:
        return BookingStatus.needs_review


def _string(value: object, fallback: str) -> str:
    text = str(value).strip() if value is not None else ""
    return text or fallback


def _list_of_strings(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]
